a = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(a))
print('Só tem espaço', a.isspace())
print('É um numero? ', a.isnumeric())
print('É um numero? ', a.isalpha())
print('É um numero? ', a.isupper())
print('É um numero? ', a.isupper())
print('É um numero? ', a.islower())
print('É um numero? ', a.istitle())